## Numpy Library 
Part -1

In [2]:
##importing the numpy

import numpy as np

In [7]:
##Creating the numpy array in list

arr= np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
## Craeting the numpy array in tuple

arr=np.array((1,2,3,4,5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
## Dimensions in array

arr=np.array(20)

print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


In [10]:
## 1D array

arr=np.array([1,2,3,4,5])

print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [18]:
## 2D array

arr=np.array([[1,2,3,],[7,8,9]])

print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [7 8 9]]
<class 'numpy.ndarray'>
2


In [20]:
## 3D array

arr=np.array([[[1,2,3,],[7,8,9]],[[4,5,6],[9,8,7]]])

print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]
<class 'numpy.ndarray'>
3


## Higher Dimensional Arrays

Creating an array with the 5 dimensiona and verify that it has 5 dimensional

In [24]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


## Numpy Array Indexing 

In [26]:
arr = np.array([1,2,3,4,5])
print(arr[4])

5


In [30]:
m=np.array([23,4,5,67,23,64,6.8,15,10,19])
print('2th place : ',m[0])
print('4th place : ',m[2])
print('6th place : ',m[4])
print('8th place : ',m[6])

2th place :  23.0
4th place :  5.0
6th place :  23.0
8th place :  6.8


## 2D Array Indexing 


In [33]:
arr =np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr)
print(arr.ndim)
print(arr[0,2])
print(arr[0,3])
print(arr[1,3])
print(arr[1,4])

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
2
30
40
90
100


Adding the first element of 1 row and last element 

In [39]:
arr =np.array([[10,20,30,40,50],[60,70,80,90,100]])

print('the first element of 1 row',arr[0,0])
print('the Second element of 2 row',arr[1,4])

print('sum of',arr[0,0]+arr[1,4])

the first element of 1 row 10
the Second element of 2 row 100
sum of 110


## Access 3D Arrays

In [42]:
arr =np.array([[[1,2,3,4],[5,6,7,8]],[[2,3,4,5],[6,7,8,9]]])

print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[2 3 4 5]
  [6 7 8 9]]]
3


In [44]:
## indexing for first array

print(arr[0,0,2])
print(arr[0,1,2])

3
7


In [46]:
## indexing for second array

print(arr[1,0,3])
print(arr[1,1,1])

5
7
