## Numpy Library

Part 2

In [3]:
import numpy as np

In [6]:
## 1D Array

arr= np.array([1,2,3,4,5])
print(arr[2])

3


In [8]:
arr=np.array([1,2,3,4,5,6])
print(arr[:4])
print(arr[::2])

[1 2 3 4]
[1 3 5]


In [9]:
## Slicing in 2D Array

arr=np.array([[1,2,3,],[4,5,6]])
print(arr[0,1])
print(arr[1,0])

2
4


# Data Type in NUmpy

i - integer

b - boolean

u - unsigned integer

f - floating

c - complex

v - fixed clund

m - time

M - datetime 

o - oject

s -string

u - unicode string


In [10]:
## Checking the datatype in numpy

a = np.array([1,2,3,4,5])
print(a.dtype)

int32


In [12]:
a = np.array(['animals','bird','fish'])
print(a.dtype)

<U7


In [15]:
## Creating array with a defined data type

arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [17]:
## Creating an array with the data type 4 bytes integer

arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Numpy Array Shape

the shpae an arrray is the number of element in each dimension

In [20]:
## Print the shape of a AD array

a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [25]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print(a.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)


## Reshape of Array

In [82]:
## Reshape from 1D to 2D Array

a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b=a.reshape(4,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [83]:
## Reshape from 1D to 3D Array

a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b=a.reshape(2,3,2)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Joining Numpy Array 


In [27]:
## 1D Array

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1)
print(arr2)
print()
arr3=np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4]
[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [34]:
## Joning 2D Array

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print()
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Splitting Numpy Array


In [36]:
## Splitting the arrray in 3Array

a=np.array([1,2,3,4,5,6])
b=np.array_split(a,3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [37]:
## Splitting the arrray in 4Array

a=np.array([1,2,3,4,5,6])
b=np.array_split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## Ravel and Flatten

Convert mutlidimensional array 1D Array

In [39]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('dimensnion is ',m.ndim)
print()
n=m.ravel()
print(n)
print('dimensnion is',n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimensnion is  3

[1 2 3 4 5 6 7 8 9]
dimensnion is 1


In [40]:
## Ravel and Flatthen are the same function

m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('dimensnion is ',m.ndim)
print()
n=m.flatten()
print(n)
print('dimensnion is',n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimensnion is  3

[1 2 3 4 5 6 7 8 9]
dimensnion is 1


## Unique Function 

Fetch the element form array which are unique

In [49]:
k=np.array([12,14,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
print()
b=np.unique(k)
c=np.unique(k,return_index=True , return_counts= True)
print()
print(b)
print()
print(c)

[12 14  6  7  9  3  4  5 22 33  7  6  9  1  2 12]


[ 1  2  3  4  5  6  7  9 12 14 22 33]

(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 14, 22, 33]), array([13, 14,  5,  6,  7,  2,  3,  4,  0,  1,  8,  9], dtype=int64), array([1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1], dtype=int64))


## Delete

In [54]:
## Deleting for 1D Array 
a=np.array([12,13,14,15])
b=np.delete(a,[2])
print(b)

[12 13 15]


In [58]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print()
y=np.delete(x,1,axis=0)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]


In [60]:
## Defining the axis in array

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print()
y=np.delete(x,1,axis=1)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]


## -------------------------------------------

In [61]:
ax=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ax)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [101]:
a=ax.shape
a1=ax.reshape
b=ax.sum(axis=0)
c=ax.sum(axis=1)
d=ax.min()
e=ax.max()
f=ax.sort()

In [102]:
print('Shape of the ax',a)
print('reshape of the ax',a1)
print('sum of the Axis 0',b)
print('sum of the Axis 1',c)
print('Min Value',d)
print('max value',e)
print('sort in array',f)

Shape of the ax (3, 3)
reshape of the ax <built-in method reshape of numpy.ndarray object at 0x0000013D5C25C990>
sum of the Axis 0 [12 15 18]
sum of the Axis 1 [ 6 15 24]
Min Value 1
max value 9
sort in array None


## Range Array

In [87]:
## Range in array

arr= np.arange(99)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [89]:
## Print even number in array

a=np.arange(2,22,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [90]:
## defined number in array
## odd number

arr=np.arange(1,23,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21]


## Numpy object Creation 

In [93]:
zero=np.zeros((2,2))
print(zero)

[[0. 0.]
 [0. 0.]]


In [96]:
ones=np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [98]:
ey=np.eye(4,4)
print(ey)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [100]:
ey=np.empty((4,4))
print(ey)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
